name: Express CI

on: push

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      # copy toàn bộ root folder ~ git clone
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Verify Node
        run: node -v

      - name: Install packages
        run: npm install