name: My First Action

on: push

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print current folder
        run: pwd

      - name: List files
        run: lsssss

      - name: Node version
        run: node -v